// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyB2T3eThJVmFtGAyiiH40p7eFG1HmpfBAo',
    appId: '1:529110185023:web:2eee6ccc37d645dc53748a',
    messagingSenderId: '529110185023',
    projectId: 'misfit-personnel',
    authDomain: 'misfit-personnel.firebaseapp.com',
    storageBucket: 'misfit-personnel.appspot.com',
    measurementId: 'G-VZPBYDTKY9',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBJpR-OuK0mTbnELlajh3pWVlmeV98IkZ0',
    appId: '1:529110185023:android:899ba5f09f880f0753748a',
    messagingSenderId: '529110185023',
    projectId: 'misfit-personnel',
    storageBucket: 'misfit-personnel.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDJ_kNyi2L55dwJpg_CTnig-uaszmK2SBo',
    appId: '1:529110185023:ios:c179026981f4230c53748a',
    messagingSenderId: '529110185023',
    projectId: 'misfit-personnel',
    storageBucket: 'misfit-personnel.appspot.com',
    iosClientId: '529110185023-qn951uuss8rs1btl4op3bneb6qqckia9.apps.googleusercontent.com',
    iosBundleId: 'com.misfit.employeManagement',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDJ_kNyi2L55dwJpg_CTnig-uaszmK2SBo',
    appId: '1:529110185023:ios:91db02e1611ed0d153748a',
    messagingSenderId: '529110185023',
    projectId: 'misfit-personnel',
    storageBucket: 'misfit-personnel.appspot.com',
    iosClientId: '529110185023-n6gudbdlo4es6tr1n7p0av95dsh9r2tg.apps.googleusercontent.com',
    iosBundleId: 'com.example.employeeManagement',
  );
}
